version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teste_backend_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_backend_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: teste_backend
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: